-- Optional one-time least-privilege setup, executed as a PostgreSQL administrator.
-- Replace placeholders before use. The application creates its own tables inside
-- DB_SCHEMA on first start; it must never receive superuser privileges.
--
-- CREATE ROLE masar_app LOGIN PASSWORD 'REPLACE_WITH_A_LONG_RANDOM_PASSWORD'
--   NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
-- CREATE DATABASE payroll OWNER masar_app;
-- REVOKE ALL ON DATABASE payroll FROM PUBLIC;
-- GRANT CONNECT, TEMPORARY ON DATABASE payroll TO masar_app;
