import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Plus,ShieldCheck,Trash2} from 'lucide-react';
import type {Company,DepartmentInfo,Employee} from '../../types';
import {api,GosiAccount,GosiDepartmentAssignment} from '../../utils/api';
import {getCurrentPeriod} from '../../utils/period';

const input='rounded-xl border border-slate-200 px-3 py-2 text-sm';
const blank=(companyId:string):GosiAccount=>({id:`gosi-account-${crypto.randomUUID()}`,companyId,registrationNumber:'',name:'',branchName:'',isDefault:false,isActive:true});
export const CompanyGosiAccountsTab=React.memo(function CompanyGosiAccountsTab({company,departments,employees,tr}:{company:Company;departments:DepartmentInfo[];employees:Employee[];tr:(ar:string,en:string)=>string}){
  const currentMonth=getCurrentPeriod(company.timezone||'Asia/Riyadh'),[mappingMonth,setMappingMonth]=useState(currentMonth),[accounts,setAccounts]=useState<GosiAccount[]>([]),[mappings,setMappings]=useState<GosiDepartmentAssignment[]>([]),[form,setForm]=useState(()=>blank(company.id)),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const active=useMemo(()=>new Map(mappings.filter(x=>x.effectiveFrom<=`${mappingMonth}-31`&&(!x.effectiveTo||x.effectiveTo>=`${mappingMonth}-01`)).map(x=>[x.departmentName,x])),[mappings,mappingMonth]);
  const load=useCallback(async()=>{const [a,m]=await Promise.all([api.listGosiAccounts(company.id),api.listGosiDepartmentAssignments(company.id)]);setAccounts(a.records);setMappings(m.records);},[company.id]);
  useEffect(()=>{setForm(blank(company.id));load().catch(e=>setMessage(e.message));},[company.id,load]);
  const save=async()=>{setBusy(true);try{await api.saveGosiAccount(form);await load();setForm(blank(company.id));setMessage(tr('تم حفظ حساب التأمينات.','GOSI account saved.'));}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  const mapDepartment=async(departmentName:string,accountId:string)=>{if(!accountId)return;setBusy(true);try{const old=active.get(departmentName);await api.saveGosiDepartmentAssignment({id:old?.accountId===accountId?old.id:`gosi-department-${crypto.randomUUID()}`,companyId:company.id,departmentName,accountId,effectiveFrom:`${mappingMonth}-01`,effectiveTo:null});await load();setMessage(tr('تم تحديث ربط القسم.','Department mapping updated.'));}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  return <div className="space-y-5"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-emerald-600"/>{tr('حسابات التأمينات للمنشأة','Company GOSI accounts')}</h3><p className="mt-1 text-xs text-slate-500">{tr('أضف كل رقم اشتراك أو فرع تأمينات تابع للمنشأة.','Add every GOSI registration belonging to the company.')}</p>{message&&<div className="mt-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{message}</div>}<div className="mt-4 grid gap-3 md:grid-cols-5"><input className={input} placeholder={tr('اسم الحساب','Account name')} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={input} placeholder={tr('رقم الاشتراك','Registration no.')} value={form.registrationNumber} onChange={e=>setForm({...form,registrationNumber:e.target.value})}/><input className={input} placeholder={tr('اسم الفرع','Branch name')} value={form.branchName} onChange={e=>setForm({...form,branchName:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/>{tr('افتراضي','Default')}</label><button disabled={busy||!form.name||!form.registrationNumber} onClick={save} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Plus className="h-4 w-4"/>{tr('إضافة','Add')}</button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{accounts.map(a=><div className="flex justify-between rounded-xl border p-3" key={a.id}><div><b>{a.name}</b><div className="font-mono text-xs text-slate-500">{a.registrationNumber} · {a.branchName||'—'}</div></div><button className="text-rose-600" onClick={async()=>{if(confirm(tr('حذف الحساب؟','Delete account?'))){await api.deleteGosiAccount(company.id,a.id);await load();}}}><Trash2 className="h-4 w-4"/></button></div>)}</div></section>
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-black">{tr('ربط الأقسام بفروع التأمينات','Department to GOSI mapping')}</h3><p className="mt-1 text-xs text-slate-500">{tr(`الربط يطبق على كل موظفي القسم، ويمكن تجاوزه من تبويب التأمينات لموظف محدد.`,`The mapping applies to all department employees and can be overridden per employee.`)}</p></div><label className="text-xs font-bold text-slate-600">{tr('ساري من شهر','Effective month')}<input type="month" className={input+' ms-2'} value={mappingMonth} onChange={e=>setMappingMonth(e.target.value)}/></label></div><div className="mt-4 overflow-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-start">{tr('القسم الإداري','Department')}</th><th className="p-3 text-start">{tr('عدد الموظفين','Employees')}</th><th className="p-3 text-start">{tr('حساب التأمينات','GOSI account')}</th></tr></thead><tbody>{departments.map(d=><tr className="border-t" key={d.id}><td className="p-3 font-bold">{d.nameAr}</td><td className="p-3">{employees.filter(e=>e.department===d.nameAr).length}</td><td className="p-3"><select className={input+' w-full'} value={active.get(d.nameAr)?.accountId||''} onChange={e=>mapDepartment(d.nameAr,e.target.value)}><option value="">{tr('غير مربوط','Unassigned')}</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name} · {a.registrationNumber}</option>)}</select></td></tr>)}</tbody></table></div></section></div>;
});
