import React,{useEffect,useRef,useState} from 'react';
import {CheckCircle2,Eraser,PenLine} from 'lucide-react';
import {api,type EmployeeAttendanceReport} from '../utils/api';

type Report=EmployeeAttendanceReport&{company:{nameAr:string;nameEn:string};employee:{employeeNo:string;nameAr:string;nameEn:string;department:string}};

export const PublicAttendanceReport:React.FC=()=>{
  const token=window.location.pathname.split('/').filter(Boolean).pop()||'';
  const [report,setReport]=useState<Report|null>(null),[comments,setComments]=useState<Record<string,string>>({}),[signatureName,setSignatureName]=useState('');
  const [signedAt,setSignedAt]=useState<string|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const canvasRef=useRef<HTMLCanvasElement>(null),drawing=useRef(false),hasInk=useRef(false);
  useEffect(()=>{api.publicAttendanceReport(token).then(data=>{setReport(data.report);setSignedAt(data.signedAt);setComments(data.response?.comments||{});setSignatureName(data.response?.signatureName||'');}).catch(()=>setError('الرابط غير صالح أو انتهت صلاحيته'));},[token]);
  const point=(event:React.PointerEvent<HTMLCanvasElement>)=>{const rect=event.currentTarget.getBoundingClientRect();return {x:(event.clientX-rect.left)*(event.currentTarget.width/rect.width),y:(event.clientY-rect.top)*(event.currentTarget.height/rect.height)};};
  const start=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(signedAt)return;drawing.current=true;hasInk.current=true;const ctx=event.currentTarget.getContext('2d'),p=point(event);ctx?.beginPath();ctx?.moveTo(p.x,p.y);event.currentTarget.setPointerCapture(event.pointerId);};
  const move=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const ctx=event.currentTarget.getContext('2d'),p=point(event);if(ctx){ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#0f172a';ctx.lineTo(p.x,p.y);ctx.stroke();}};
  const clear=()=>{const canvas=canvasRef.current;canvas?.getContext('2d')?.clearRect(0,0,canvas.width,canvas.height);hasInk.current=false;};
  const save=async()=>{if(!report||signatureName.trim().length<2||!hasInk.current){setError('اكتب الاسم وارسم التوقيع قبل الحفظ');return;}setSaving(true);setError('');try{const result=await api.respondToAttendanceReport(token,{signatureName:signatureName.trim(),signatureData:canvasRef.current?.toDataURL('image/png')||'',comments});setSignedAt(result.signedAt);}catch{setError('تعذر حفظ الإقرار. ربما تم توقيعه مسبقًا أو انتهت صلاحية الرابط.');}finally{setSaving(false);}};
  if(error&&!report)return <main dir="rtl" className="min-h-screen bg-slate-100 p-6 flex items-center justify-center"><div className="rounded-3xl bg-white p-8 font-bold text-rose-700 shadow">{error}</div></main>;
  if(!report)return <main className="min-h-screen bg-slate-100"/>;
  return <main dir="rtl" className="min-h-screen bg-slate-100 p-3 sm:p-8 text-slate-900"><section className="mx-auto max-w-5xl rounded-3xl bg-white p-4 sm:p-8 shadow-xl">
    <header className="border-b pb-5"><h1 className="text-2xl font-black">كشف الحضور والانصراف</h1><p className="mt-2 font-bold">{report.company.nameAr}</p><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><span>الموظف: <b>{report.employee.nameAr||report.employee.nameEn}</b></span><span>الرقم: <b>{report.employee.employeeNo}</b></span><span>الفترة: <b>{report.periodMonth}</b></span></div></header>
    <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-100"><tr>{['التاريخ','الدوام','الدخول','الخروج','الحالة','التأخير','ملاحظة الموظف'].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{report.records.map(row=><tr key={row.id} className="border-b"><td className="p-3 font-mono">{row.date}</td><td className="p-3">{row.scheduledStart||'—'} - {row.scheduledEnd||'—'}</td><td className="p-3">{row.actualCheckIn||'—'}</td><td className="p-3">{row.actualCheckOut||'—'}</td><td className="p-3 font-bold">{row.status}</td><td className="p-3">{row.delayMinutes} د</td><td className="p-2"><textarea disabled={Boolean(signedAt)} value={comments[row.id]||''} maxLength={1000} onChange={e=>setComments({...comments,[row.id]:e.target.value})} className="min-h-16 w-full rounded-xl border p-2 disabled:bg-slate-50" placeholder="تعليق اختياري على هذا اليوم"/></td></tr>)}</tbody></table></div>
    <div className="mt-6 rounded-2xl border bg-slate-50 p-5">{signedAt?<div className="flex items-center gap-2 font-black text-emerald-700"><CheckCircle2/>تم توقيع الإقرار إلكترونيًا بتاريخ {new Date(signedAt).toLocaleString('ar-SA')}</div>:<><h2 className="flex items-center gap-2 font-black"><PenLine className="h-5 w-5"/>إقرار وتوقيع الموظف</h2><p className="mt-2 text-xs text-slate-600">أقر بأنني راجعت الكشف، وأثبتت ملاحظاتي إن وجدت، وأوافق على حفظ اسمي وتوقيعي ووقت الإرسال كإقرار إلكتروني.</p><input value={signatureName} onChange={e=>setSignatureName(e.target.value)} maxLength={160} placeholder="الاسم الكامل" className="mt-4 w-full rounded-xl border bg-white p-3"/><div className="mt-3 overflow-hidden rounded-xl border bg-white"><canvas ref={canvasRef} width={900} height={220} onPointerDown={start} onPointerMove={move} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false} className="h-40 w-full touch-none" aria-label="مساحة التوقيع"/></div><div className="mt-3 flex flex-wrap justify-between gap-2"><button type="button" onClick={clear} className="flex items-center gap-2 rounded-xl border px-4 py-2 font-bold"><Eraser className="h-4 w-4"/>مسح التوقيع</button><button type="button" disabled={saving} onClick={save} className="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white disabled:opacity-50">{saving?'جارٍ الحفظ…':'حفظ وإرسال الإقرار'}</button></div>{error&&<p className="mt-3 font-bold text-rose-700">{error}</p>}</>}</div>
  </section></main>;
};
