import {strToU8,zipSync} from 'fflate';

type Amounts={subjectWage:number;employerShare:number;employeeShare:number;total:number};
type Item={status:string;employeeNo:string;employeeName:string;subscriberName:string;identity:string;department:string;assignedAccountId:string|null;assignmentSource:string|null;actual:Amounts;expected:Amounts;difference:Amounts;paymentMode:string;salaryDeduction:number;companyBurden:number;companyCoveredEmployeeShare:number};
type Result={invoice:{accountName:string;registrationNumber:string;invoiceMonth:string;payrollMonth:string;sourceFileName:string};summary:{actual:Amounts;expected:Amounts;difference:Amounts;[key:string]:unknown};comparisons:Item[]};
const esc=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const col=(i:number)=>{let s='';for(let n=i+1;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
const cell=(ref:string,v:unknown,style=0)=>typeof v==='number'?`<c r="${ref}" s="${style}"><v>${Number.isFinite(v)?v:0}</v></c>`:`<c r="${ref}" t="inlineStr" s="${style}"><is><t>${esc(v)}</t></is></c>`;
const row=(n:number,values:unknown[],style=0)=>`<row r="${n}">${values.map((v,i)=>cell(`${col(i)}${n}`,v,style)).join('')}</row>`;
const worksheet=(rows:string,last:string,widths:number[])=>`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${last}"/><sheetViews><sheetView rightToLeft="1" workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${rows}</sheetData></worksheet>`;

export function exportGosiComparisonXlsx(result:Result,accounts:Map<string,string>):void{
  const statuses:Record<string,string>={MATCHED:'مطابق',DIFFERENT:'يوجد اختلاف',INVOICE_ONLY:'بالفاتورة فقط',PAYROLL_ONLY:'بالمسير فقط',UNASSIGNED_ACCOUNT:'غير مربوط بحساب',WRONG_ACCOUNT:'حساب مختلف',MISSING_IN_PAYROLL:'غير موجود بالمسير'};
  const source=(v:string|null)=>v==='EMPLOYEE'?'استثناء موظف':v==='DEPARTMENT'?'ربط القسم':'غير مربوط',keys:[string,keyof Amounts][]=[['الأجر الخاضع','subjectWage'],['حصة الشركة','employerShare'],['حصة الموظف','employeeShare'],['الإجمالي','total']];
  const summary=[row(1,['البيان','القيمة'],1),row(2,['حساب التأمينات',result.invoice.accountName]),row(3,['رقم الاشتراك',result.invoice.registrationNumber]),row(4,['شهر الفاتورة',result.invoice.invoiceMonth]),row(5,['شهر المسير',result.invoice.payrollMonth]),row(6,['اسم الملف',result.invoice.sourceFileName]),row(8,['البند','الفاتورة','المسير','الفرق'],1),...keys.map(([label,key],i)=>row(i+9,[label,result.summary.actual[key],result.summary.expected[key],result.summary.difference[key]])),row(14,['الحالة','العدد'],1),...Object.entries(statuses).map(([key,label],i)=>row(i+15,[label,Number(result.summary[key]||0)]))].join('');
  const headers=['الحالة','رقم الموظف','اسم الموظف','الهوية/الإقامة','القسم الإداري','حساب التأمينات','مصدر الربط','طريقة التحمل','المخصوم من الموظف','إجمالي تحمل الشركة','حصة الموظف التي تحملتها الشركة','أجر الفاتورة','أجر المسير','فرق الأجر','حصة الشركة بالفاتورة','حصة الشركة النظامية بالمسير','فرق الشركة','حصة الموظف بالفاتورة','حصة الموظف النظامية بالمسير','فرق الموظف','إجمالي الفاتورة','إجمالي المسير','إجمالي الفرق'];
  const details=[row(1,headers,1),...result.comparisons.map((x,i)=>row(i+2,[statuses[x.status]||x.status,x.employeeNo,x.employeeName||x.subscriberName,x.identity,x.department,accounts.get(x.assignedAccountId||'')||'',source(x.assignmentSource),x.paymentMode==='COMPANY_FULL'?'الشركة تتحمل كامل الاشتراك':x.paymentMode==='SHARED'?'مشترك':'على المنشأة فقط',x.salaryDeduction,x.companyBurden,x.companyCoveredEmployeeShare,x.actual.subjectWage,x.expected.subjectWage,x.difference.subjectWage,x.actual.employerShare,x.expected.employerShare,x.difference.employerShare,x.actual.employeeShare,x.expected.employeeShare,x.difference.employeeShare,x.actual.total,x.expected.total,x.difference.total]))].join('');
  const workbook=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="ملخص المقارنة" sheetId="1" r:id="rId1"/><sheet name="تفاصيل الموظفين" sheetId="2" r:id="rId2"/></sheets></workbook>`;
  const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF047857"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0"/></cellXfs></styleSheet>`;
  const types=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`;
  const root=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
  const file=zipSync({'[Content_Types].xml':strToU8(types),'_rels/.rels':strToU8(root),'xl/workbook.xml':strToU8(workbook),'xl/_rels/workbook.xml.rels':strToU8(rels),'xl/styles.xml':strToU8(styles),'xl/worksheets/sheet1.xml':strToU8(worksheet(summary,'D21',[28,28,18,18])),'xl/worksheets/sheet2.xml':strToU8(worksheet(details,`W${result.comparisons.length+1}`,[18,14,28,20,20,24,18,24,18,18,22,16,16,16,18,20,16,18,20,16,16,16,16]))},{level:6});
  const url=URL.createObjectURL(new Blob([file],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=document.createElement('a');link.href=url;link.download=`GOSI_Comparison_${result.invoice.invoiceMonth}_${result.invoice.payrollMonth}.xlsx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);
}
